on:
  workflow_dispatch:
  ## Uncomment below if you want run it everyday
  #schedule:
  #- cron: "0 0 * * *"

permissions: write-all

env:
  BRANCH: 2022-summer # Change this before push to new branch

jobs:
  task:
    name: Task
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: 
          fetch-depth: 0
          ref: ${{env.BRANCH}}
      ## Uncomment step below if you using clash, also uncomment playwright.config.ts launchOptions part
      # - name: Setup clash
      #   uses: OtaDou/setup-clash@v1
      #   with:
      #     subscription_url: ${{ secrets.SUBSCRIPTION_URL }}
      #     proxies_name_regex: ${{ secrets.SUBSCRIPTION_REGEX }}
      # - run: curl -s --proxy "http://127.0.0.1:11223" ipinfo.io | jq .country
      - name: Run task
        run: |
          git config --local user.email "action@github.com" && git config --local user.name "GitHub Action"
          npx playwright install
          npx playwright install-deps chromium
          yarn
          npx playwright test || echo fail
          node history2md.js ${{ env.BRANCH }} HISTORY.csv README.md
          git add . && git commit -m "update" -a
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.BRANCH }}